# Generated by Django 6.0.8 on 2026-08-31 13:12

import pgvector.django.vector
from django.db import migrations, models

from evennia_ai_memory.config import get_embedding_dimensions

# Read at apply time, not frozen, so the column is created at whatever
# width the consuming project configured. Changing it once rows exist
# means re-embedding them — vectors of two widths are not comparable.
_DIMENSIONS = get_embedding_dimensions()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoreMemory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('scope_level', models.CharField(db_index=True, max_length=20)),
                ('scope_tags', models.JSONField(default=list)),
                ('embedding', models.BinaryField(blank=True, null=True)),
                ('embedding_vector', pgvector.django.vector.VectorField(blank=True, dimensions=_DIMENSIONS, null=True)),
                ('source', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'lore memory',
                'verbose_name_plural': 'lore memories',
                'indexes': [models.Index(fields=['scope_level'], name='evennia_ai__scope_l_f5f62a_idx'), models.Index(fields=['scope_level', 'created_at'], name='evennia_ai__scope_l_5ffc58_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'title'), name='uniq_lorememory_source_title')],
            },
        ),
        migrations.CreateModel(
            name='NpcMemory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npc_uuid', models.UUIDField(db_index=True)),
                ('pc_uuid', models.UUIDField(db_index=True)),
                ('pc_name', models.CharField(max_length=80)),
                ('summary', models.TextField()),
                ('interaction_type', models.CharField(default='say', max_length=40)),
                ('initiator', models.CharField(default='pc', max_length=8)),
                ('embedding', models.BinaryField(blank=True, null=True)),
                ('embedding_vector', pgvector.django.vector.VectorField(blank=True, dimensions=_DIMENSIONS, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'NPC memory',
                'verbose_name_plural': 'NPC memories',
                'indexes': [models.Index(fields=['npc_uuid', 'created_at'], name='evennia_ai__npc_uui_751ab8_idx'), models.Index(fields=['npc_uuid', 'pc_uuid'], name='evennia_ai__npc_uui_7255d8_idx')],
            },
        ),
    ]
