# Generated by Django 6.0.8 on 2026-10-06 17:27

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models

from evennia_ai_memory.config import get_embedding_dimensions

# Read at apply time, as 0001 does, so the column matches the configured width.
_DIMENSIONS = get_embedding_dimensions()

class Migration(migrations.Migration):

    dependencies = [
        ('evennia_ai_memory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_uuid', models.UUIDField(db_index=True)),
                ('summary', models.TextField()),
                ('record', models.TextField(blank=True, default='')),
                ('analysis', models.JSONField(default=dict)),
                ('embedding', models.BinaryField(blank=True, null=True)),
                ('embedding_vector', pgvector.django.vector.VectorField(blank=True, dimensions=_DIMENSIONS, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['owner_uuid', 'created_at'], name='evennia_ai__owner_u_cf43e0_idx')],
            },
        ),
        migrations.CreateModel(
            name='EncounterParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=80)),
                ('side', models.CharField(max_length=40)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='evennia_ai_memory.encounter')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantTrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40)),
                ('value', models.IntegerField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traits', to='evennia_ai_memory.encounterparticipant')),
            ],
        ),
    ]
